# Site settings
title: IKKIson CS, Dev Blog
url: "https://ikkison.github.io/"    # the protocol and hostname of your site, eg. `http://zhaoyuxiang.cn/blog`
baseurl: "https://ikkison.github.io/index.html" # the prefix of your site uri, eg. `/bohu-jekyll-theme` or just one slash `/`
#timezone: Asia/Shanghai
description: 손익현의 CS, 개발 블로그
# Your information
email: shout2517@naver.com
author: IKKIson
place: ROK
domain: 
company: 
position: 
school:
major: Computer Science
resume: "https://ikkison.github.io/"
profile: Money Makes Science, Technology Makes Money
twitter_username: 
weibo_username: 
github_username: IKKIson

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
disqus_shortname: IKKIson
# get one: https://disqus.com/admin/signup/
# duoshuo_shortname: IKKIson  
# get one: http://duoshuo.com/create-site/

permalink: /archivers/:title
gems:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 2
paginate_path: "/page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
